version: "3"
networks:
  backend:
    driver: bridge

services:
  app:
    build: ./app
    container_name: flask-app
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0.21
    container_name: flask-mysql-db
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE